menu:
- {name: 'papers', url: '/papers'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', label: 'GitHub', link: 'https://github.com/joonhyeokyim'}
- {icon: 'linkedin', label: 'LinkedIn', link: 'https://www.linkedin.com/in/joon-hyeok-yim-391307127/'}

contacts:
- {name: 'Joon-Hyeok Yim', email: 'joonhyeokyim@gmail.com'}
